---
- name: Vervang NGINX door Apache webserver
  hosts: ubuntu_servers
  become: true
  tasks:
    - name: Stop en verwijder NGINX als het geïnstalleerd is
      apt:
        name: nginx
        state: absent
        purge: yes
        autoremove: yes
      when: ansible_facts.packages.nginx is defined

    - name: Verwijder eventuele NGINX configuratiebestanden
      file:
        path: /etc/nginx
        state: absent

    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Installeer Apache2 webserver
      apt:
        name: apache2
        state: present

    - name: Zorg dat Apache gestart is en automatisch opstart
      service:
        name: apache2
        state: started
        enabled: yes
