---
- name: Update alle Ubuntu servers en deploy zxHOSTING Welkomspagina
  hosts: all
  become: true
  vars:
    html_dest: /var/www/html/index.html

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Installeer Nginx (indien niet aanwezig)
      apt:
        name: nginx
        state: present

    - name: Zorg dat Nginx draait en enabled is
      service:
        name: nginx
        state: started
        enabled: true

    - name: Standaard Nginx index.html verwijderen
      file:
        path: /var/www/html/index.html
        state: absent

    - name: Deploy welkomspagina (index.html)
      copy:
        dest: "{{ html_dest }}"
        content: |
          <!DOCTYPE html>
          <html lang="nl">
          <head>
            <meta charset="UTF-8">
            <title>Welkom bij zxHOSTING.NL</title>
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <style>
              body {
                margin: 0;
                height: 100vh;
                background: #181824 linear-gradient(120deg, #181824 60%, #432c7a 100%);
                color: #f0f0f0;
                font-family: 'Segoe UI', Arial, sans-serif;
                display: flex;
                flex-direction: column;
                justify-content: center;
                align-items: center;
              }
              .container {
                background: rgba(34,34,44,0.95);
                border-radius: 12px;
                box-shadow: 0 8px 40px 0 rgba(58,71,212,0.2);
                padding: 3rem 2.5rem;
                text-align: center;
                max-width: 420px;
              }
              h1 {
                font-size: 2.3rem;
                margin-bottom: 1rem;
                background: linear-gradient(90deg, #D72660, #3FCEAC, #F9CB40, #6C4AB6, #F96E46);
                -webkit-background-clip: text;
                -webkit-text-fill-color: transparent;
                background-clip: text;
              }
              .tagline {
                font-size: 1.1rem;
                margin-bottom: 1.5rem;
                color: #cfd8dc;
              }
              .cta {
                display: inline-block;
                margin-top: 20px;
                padding: 12px 32px;
                border: none;
                border-radius: 7px;
                background: linear-gradient(90deg, #3fceac, #f96e46);
                color: white;
                font-weight: 600;
                font-size: 1rem;
                text-decoration: none;
                box-shadow: 0 4px 16px rgba(63,206,172,0.1);
                transition: background .3s, transform .3s;
              }
              .cta:hover {
                background: linear-gradient(90deg, #F96E46, #3FCEAC);
                transform: translateY(-2px) scale(1.05);
              }
            </style>
          </head>
          <body>
            <div class="container">
              <h1>Welkom bij zxHOSTING.NL</h1>
              <div class="tagline">
                De betrouwbare partner voor uw webhosting.<br>
                Snel. Veilig. Professioneel.
              </div>
              <a class="cta" href="https://mail.zxhosting.nl">Bezoek onze website</a>
            </div>
          <audio controls src="http://v-domain.nl/r1/;"></audio>
          <audio controls src="http://v-domain.nl/r2/;"></audio>
          </body>
          </html>
        owner: www-data
        group: www-data
        mode: '0644'
